node {
    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    stage('Test') {
        try {
            docker.image('qnib/pytest').inside {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        } catch (Exception e) {
            currentBuild.result = 'UNSTABLE'
        } finally {
            junit 'test-reports/results.xml'
        }
    }
    stage('Manual Approval') {
        input message: "Lanjutkan ke tahap Deploy?", ok: "Proceed"
    }

    stage('Deploy') {
        echo "Sedang melakukan proses deployment..."
        sleep time: 60, unit: 'SECONDS'
        echo "Deployment selesai!"
    }
}
